### ISSUE TITLE
Can't compile to Android target: _hx_reslove_virtual_array not declared

### ISSUE THREAD

**Issue by nightblade9** [haxelime/lime#1251]
I have a simple HaxeFlixel app I built with a previous version of Flixel. I upgraded to 4.5.1 with OpenFL 8.6.4 and Lime 7.1.1. I can compile and run against `neko` fine.

When I run `lime test android`, I get this error:

```
Error: ./src/haxe/Unserializer.cpp: In member function 'Dynamic haxe::Unserializer_obj::unserialize()':
./src/haxe/Unserializer.cpp:329: error: '_hx_reslove_virtual_array' was not declared in this scope
In file included from ./src/lime/_internal/backend/native/NativeOpenGLRenderContext.cpp:360:
include/lime/graphics/opengl/ext/QCOM_tiled_rendering.h:45: warning: this decimal constant is unsigned only in ISO C90
```

It looks like a typo (`resolve` => `reslove`). I believe (am not 100% certain) I also tried with HaxeFlixel 4.4.2 and OpenFL 2.x with lime 3.6.0 (I think), and got a similar error.

To be sure, I deleted all my (multiple) versions of Flixel/Lime/etc. installed and reinstalled the latest, which gives me this error.

How can I resolve this?

**Comment by player-03** [comment]
Resolved (or "resloved") in HaxeFoundation/haxe#5983. Seems they've kept the typo.
