### ISSUE TITLE
Behavior difference of lime test html5 between Windows and Linux

### ISSUE THREAD

**Issue by vulpivia** [haxelime/lime#1259]
The behavior of `lime test html5` differs between Windows and Linux. On Windows, the web browser automatically opens when the command is run. On Linux nothing happens but http://127.0.0.1:3000/ can still be opened.

Tested under Windows 10 and Ubuntu Mate 18.04 with [this](https://github.com/Acid147/rpg-game) project and Firefox as the default web browser.

#955 is probably related.

**Comment by jgranick** [comment]
Can you try `xdg-open path/to/index.html`?

This should be set in your distribution to use the default browser.

**Comment by Acid147** [comment]
I tried it again and found that it launches just fine if I use `lime test html5`. What doesn't work is `sudo lime test html5` which I previously used because it is required if I choose Linux as the build target.

**Comment by Acid147** [comment]
The application that opens HTML files is Visual Studio Code for my user account and the root account.

**Comment by player-03** [comment]
Closing because it seems you figured this out.
