### ISSUE TITLE
"default" Asset library path is incorrect, crashes on start

### ISSUE THREAD

**Issue by keyreal-code** [haxelime/lime#1331]
Hello,

Getting the following error: `[lime.utils.Preloader] ERROR: There is no asset library with an ID of "default"` when trying to start a Lime application (porting an existing game engine to a newer Lime).

Native target, Windows, _develop_ branch.

Traced down the problem to `Assets.loadLibrary`, which sets `path` to "/manifest/default.json". Adding a line that changes `path` to "manifest/default.json" (without the leading slash) before calling `AssetManifest.loadFromFile` fixes the issue.

I'm not sure what is the actual cause of this bug, so I can't provide a meaningful pull request at this point.

**Comment by keyreal-code** [comment]
Another issue, which might be related to this: unembedded assets are not loaded and result in a crash.

I'm calling `Assets.getImage("textures/perlin.png")` in the code. The image file exists. The project.xml contains the following line: `<assets if="dev" path="assets/textures" rename="textures" embed="false" />`

The id "textures/perlin.png" is eventually passed to `AssetLibrary.getImage`, where it attempts to resolve the path by calling `paths.get(id)`, which returns the string `//..//textures/perlin.png`. This is passed to `Image.fromFile` which then eventually throws a NPE.

Embedded assets seem to be loaded fine.

**Comment by keyreal-code** [comment]
It seems like the second problem happens because the basePath in AssetManifest is set to `//..//`. Forcefully setting it to blank character `` solves this.

**Comment by ianharrigan** [comment]
I also, seemingly suddenly, hit this issue. Using the proposed fix:

```haxe
if (path == "/manifest/default.json") {
    path = "manifest/default.json";
}
```
in `lime.utils.Assets` seemed to get past the crash, however, it also seems that now i cant actually get any of the resources (listed in an `include.xml` from a haxelib project)

This was an app that was previously working, i did do an `openfl upgrade` and i think the only thing that updated was hxcpp... not sure if that might help to get to the root of the issue.

Cheers,
Ian

**Comment by AlexHaxe** [comment]
I had the same issue on a Windows system that was updated to hxcpp 4.0.19. The app would compile and run fine on Linux and neko (Linux and Windows), but on C++ it would show a message box complaining about missing `default` asset library and a stacktrace (when running with `-debug`) or simply show a white screen with a frozen progress bar (without `-debug`).

My fix was to go back to hxpcpp 4.0.8 (that's the version I had running before, there might be later versions that also fix the issue)

**Comment by ianharrigan** [comment]
I can confirm @AlexHaxe's solution. Reverting back to `hxcpp:4.0.8` makes the issue go away.

**Comment by Gama11** [comment]
I just found that this only happens when latest hxcpp is used together with Haxe 4.0.0-rc.2. Hxcpp 4.0.19 seems to work fine with rc.3.

**Comment by Gama11** [comment]
This has been fixed in hxcpp:

- https://github.com/HaxeFoundation/hxcpp/issues/814
- https://github.com/HaxeFoundation/hxcpp/commit/d119a07ef9e41b938fb4aebb3e6469c22c1e536f
