### ISSUE TITLE
Cannot setup lime

### ISSUE THREAD

**Issue by NulllStack** [haxelime/lime#1353]
![image](https://user-images.githubusercontent.com/47838437/64493989-cfe22d80-d2b9-11e9-8dcf-d26f9019a690.png)

**Comment by NulllStack** [comment]
it seems that version 7.5.0 does not have this problem

**Comment by NulllStack** [comment]
im trying to setup lime on my laptop and desktop, they have the same result as the figure shown

**Comment by aW4KeNiNG** [comment]
Same error here.

**Comment by aW4KeNiNG** [comment]
The problem happens because lime.exe and openfl.exe are 32 bits version. If you have installed the haxe 64 bits version then it doesn't work.

**Comment by NulllStack** [comment]
> The problem happens because lime.exe and openfl.exe are 32 bits version. If you have installed the haxe 64 bits version then it doesn't work.

But there is no problem with version 7.6.0.

**Comment by player-03** [comment]
Is it safe to assume that with Haxe 4 released, this is fixed?
