### ISSUE TITLE
ios test > Uncaught exception - Invalid field access : id

### ISSUE THREAD

**Issue by vdotup** [haxelime/lime#1355]
hi this is my first try to test for ios and i get this error i tried new empty project and i get the same please someone explain thank you

mac os
vscode

** BUILD SUCCEEDED **

Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 641
Called from lime/tools/PlatformTarget.hx line 129
Called from IOSPlatform.hx line 438
Called from lime/tools/IOSHelper.hx line 318
Called from lime/tools/XCodeHelper.hx line 104
Uncaught exception - Invalid field access : id

**Comment by PlutoniumBytes** [comment]
Had the same issue,

The default iphone simulator seems to be not supported any longer:
`private static inline var DEFAULT_IPHONE_SIMULATOR = "iphone-6";`

Set it to 
`private static inline var DEFAULT_IPHONE_SIMULATOR = "iphone-11";`
and it should work again ( after you rebuild the lime tools ).

@jgranick Please add this :)
