### ISSUE TITLE
App craches when textfield loses focus on Android (lime 7.7.0, openFL 8.9.6)

### ISSUE THREAD

**Issue by m0rkeulv** [haxelime/lime#1385]
After upgrading to lime 7.7.0 my app crashes when i select a Textfield and then click elsewhere on the screen so the Textfield loses focus, it does not matter if i type anything or not, it will crash once it loses focus. 

I have tested this on Windows and Android and this only happens on Android, Windows works just fine. i also want to note that everything works just fine with lime 7.6.3 so from what i can tell this is something that broke in  7.7.0

to reproduce just create a input Textfield,  build and test  on Android.  once in the app select the input field then click anywhere else to lose focus.

**Comment by jgranick** [comment]
Does this help? https://github.com/haxelime/lime/commit/5a99ef3175e9647d0d7fba16ee9302bffa62a8e7

**Comment by m0rkeulv** [comment]
it Looks like that solved the problem :)
```
- checked out develop branch of lime
- lime rebuild tools
- lime rebuild android
- openfl test android
- tested textfields on android, did not crash :D
```
