### ISSUE TITLE
Where do I find replacement if executable file is not clickably?

### ISSUE THREAD

**Issue by SourceSkyBoxer** [haxelime/lime#1389]
Hello everyone, 

Create HelloWorld from "lime create HelloWorld" and "lime test linux -v
I saw because executable file is not clickable than I need change to Export/linux/obj
and scroll up and find terminal line:
`g++ -o Main -rdynamic -m64 @obj/linux64-stat/all_objs /home/jens/Build-Developments/lime/ndll/Linux64/liblime.a /home/jens/Build-Developments/hxcpp/lib/Linux64/liblinuxcompat.a -lpthread -lrt libApplicationMain.a -ldl`
than past to end of terminal line empty 
`g++ -o Main -rdynamic -m64 @obj/linux64-stat/all_objs /home/jens/Build-Developments/lime/ndll/Linux64/liblime.a /home/jens/Build-Developments/hxcpp/lib/Linux64/liblinuxcompat.a -lpthread -lrt libApplicationMain.a -ldl -no-pie`

Than executable file should be clickable.
Copy from Main and past to Export/linux/bin/
Simple 
cp -f Main ../bin/HelloWorld

Than result looks like clickable executable file:
![image](https://user-images.githubusercontent.com/57066679/77599134-1456b300-6f04-11ea-86d0-318c9ebab7e3.png)

How do I add "-no-pie" in compilation of Haxe.

Best regards

**Comment by jgranick** [comment]
Try editing the HXCPP toolchain:

https://github.com/HaxeFoundation/hxcpp/blob/master/toolchain/linux-toolchain.xml

If it works out well for you I suggest putting in a pull request, I didn't realize this was the only difference!

Any idea how to get an icon attached to it?

**Comment by SourceSkyBoxer** [comment]
Hello my best @jgranick thanks
Yes different because Ubuntu 18.04's gcc doesn't have no-pie format. If you click executable file on Nautilus. 
I add `<flag value="-no-pie" />` before `<lib name="-ldl" />`
than it works fine like normal executable file.
