### ISSUE TITLE
ZLib dependency has broken

### ISSUE THREAD

**Issue by ngrebenshikov** [haxelime/lime#1393]
The development version of HXCPP doesn't have ${HXCPP}/project/libs/zlib/ZLib.cpp that is used when LIME_ZLIB is set.

It was removed in https://github.com/HaxeFoundation/hxcpp/commit/e431d92809a521444594010cbe0dce4b836f6f18#diff-46f86faa6bbf9ac94a7e459509a20ed0

**Comment by player-03** [comment]
Seems to have been fixed in 0d790f3.
