### ISSUE TITLE
Numerous 'identifier not found' errors compiling to cpp with Haxe 4.1

### ISSUE THREAD

**Issue by intoxopox** [haxelime/lime#1399]
I imagine this comes down to hxcpp, but I'm getting numerous 'identifier not found' errors when compiling any Lime or OpenFL project to cpp.
For example:
```
Error: Image.cpp
./src/lime/graphics/Image.cpp(305): error C2039: 'IsPointerEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/graphics/Image.cpp(305): error C3861: 'IsPointerEq': identifier not found
./src/lime/graphics/Image.cpp(473): error C2039: 'IsInstanceEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/graphics/Image.cpp(473): error C3861: 'IsInstanceEq': identifier not found
./src/lime/graphics/Image.cpp(491): error C2039: 'IsInstanceEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/graphics/Image.cpp(491): error C3861: 'IsInstanceEq': identifier not found
```
I've tried switching from latest hxcpp release to what's current on git. Tried rebuilding hxcpp and rebuilding hxcpp tools, followed by rebuilding lime windows and lime tools. No change. Is there something else I should try?

This seems of note: https://github.com/HaxeFoundation/hxcpp/commit/4a385e05fca18cb69cc79091793d85616d5372d3

**Comment by intoxopox** [comment]
Another example:
```
Error: BMP.cpp
./src/lime/_internal/format/BMP.cpp(137): error C2039: 'IsPointerEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/_internal/format/BMP.cpp(137): error C3861: 'IsPointerEq': identifier not found
./src/lime/_internal/format/BMP.cpp(156): error C2039: 'IsPointerEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/_internal/format/BMP.cpp(156): error C3861: 'IsPointerEq': identifier not found
./src/lime/_internal/format/BMP.cpp(168): error C2039: 'IsPointerEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/_internal/format/BMP.cpp(168): error C3861: 'IsPointerEq': identifier not found
./src/lime/_internal/format/BMP.cpp(215): error C2039: 'IsPointerEq': is not a member of 'hx'
G:/Installs/HaxeToolkit/haxe/lib/hxcpp/4,1,1/include\hx/LessThanEq.h(4): note: see declaration of 'hx'
./src/lime/_internal/format/BMP.cpp(215): error C3861: 'IsPointerEq': identifier not found```

**Comment by intoxopox** [comment]
UPDATE:
I uninstalled OpenFL, Lime, and Hxcpp via haxelib. Then installed Haxe nightly (haxe-4.2.0-rc.1+354c24d30-win). Then grabbed latest Hxcpp, Lime, and OpenFL from git and rebuilt everything. The above lime-specific issues are no longer occurring.
Should I go ahead and close this issue, or leave it open until next release?

**Comment by ShaunHolt** [comment]
I'm getting them as well..... i'll check hxcpp..... i know the rest is updated to newest gits.

Compiling group: haxe
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -m64 -DHXCPP_M64 -I/home/shaunholt/haxelib/hxcpp/4,1,1/include ... tags=[haxe,static]
 - src/lime/media/openal/AL.cpp  [haxe,release]
 - src/haxe/ui/containers/dialogs/DialogEvent.cpp 
 - src/lime/_internal/format/BMP.cpp  [haxe,release]
 - src/openfl/_internal/formats/swf/SWFLiteLibrary.cpp  [haxe,release]
 - src/haxe/ui/util/MathUtil.cpp 
Error: ./src/lime/_internal/format/BMP.cpp: In static member function ‘static haxe::io::Bytes lime::_internal::format::BMP_obj::encode(lime::graphics::Image, lime::_internal::format::BMPType)’:
./src/lime/_internal/format/BMP.cpp:134:26: error: ‘IsPointerEq’ is not a member of ‘hx’
  134 | HXDLIN(  69)   if (::hx::IsPointerEq( type,::lime::_internal::format::BMPType_obj::ICO_dyn() )) {
      |                          ^~~~~~~~~~~
./src/lime/_internal/format/BMP.cpp:153:26: error: ‘IsPointerEq’ is not a member of ‘hx’
  153 | HXDLIN(  73)   if (::hx::IsPointerEq( type,::lime::_internal::format::BMPType_obj::RGB_dyn() )) {
      |                          ^~~~~~~~~~~
./src/lime/_internal/format/BMP.cpp:165:26: error: ‘IsPointerEq’ is not a member of ‘hx’
  165 | HXDLIN(  75)   if (::hx::IsPointerEq( type,::lime::_internal::format::BMPType_obj::BITFIELD_dyn() )) {
      |                          ^~~~~~~~~~~
./src/lime/_internal/format/BMP.cpp:212:25: error: ‘IsPointerEq’ is not a member of ‘hx’
  212 | HXLINE(  88)  if (::hx::IsPointerEq( type,::lime::_internal::format::BMPType_obj::BITFIELD_dyn() )) {
      |                         ^~~~~~~~~~~

**Comment by ShaunHolt** [comment]
Downloading hxcpp from git and doing a rebuild fix it for me.
