### ISSUE TITLE
"No uncompress support" exception in haxe.zip.Reader.unzip()

### ISSUE THREAD

**Issue by starry-abyss** [haxelime/lime#1400]
For some reason lime 7.7.0 bundles a copy of haxe.zip.Reader which is only implemented for neko. When compiling a program that uses haxe.zip.Reader on hxcpp, I have this incomplete lime's version included instead of Haxe's native one. If I remove the zip package from lime codebase, the program has no problems with uncompression then.

**Comment by thomasjwebb** [comment]
I'm having the same problem. Is there a way to force it to just use the base haxe version instead without having to modify lime?
