### ISSUE TITLE
Can't compile for hl

### ISSUE THREAD

**Issue by starry-abyss** [haxelime/lime#1403]
lime version 7.7.0
haxe version 3.4.7

`> lime test hl`

`/home/igor/build/haxe/lib/lime/7,7,0/src/lime/_internal/backend/native/NativeHTTPRequest.hx:41: characters 35-46 : Type not found : Deque`

Same on two projects.

**Comment by giuppe** [comment]
Hi,
as far as I know HashLink is not included in Haxe < 4.0, so it should not work with your Haxe version.

**Comment by starry-abyss** [comment]
Are you sure?
On https://hashlink.haxe.org they state "Compiling to HL requires Haxe 3.4+"

**Comment by Gama11** [comment]
Sure, but just because Haxe 3.4 supports HL doesn't mean that Lime's HL support also works with Haxe 3.4. From the error it looks like Lime needs `sys.thread.Deque` for the HL target, which wasn't available yet in Haxe 3.4.

**Comment by starry-abyss** [comment]
Got it, thanks!

**Comment by loudoweb** [comment]
I think we can close this issue.

**Comment by starry-abyss** [comment]
Well, only pet projects can afford being always on latest everything with zero compatibility for previous versions, but suit yourself

**Comment by player-03** [comment]
I'd say it's worth adding a better error message, so that users know what they can do about it.

```xml
<log error="Lime ${lime} requires Haxe 4.0 to compile to HashLink" if="hl ${${haxe_ver} < 4.0}" />
```

**Comment by loudoweb** [comment]
> Well, only pet projects can afford being always on latest everything with zero compatibility for previous versions, but suit yourself

What an elegant way to write! Does your head still fit through the door?

It took me one day to switch my big project from openfl 3.6.1 to last openFL to make it compile for HL. Of course, you may have more dependencies that I had, but if you need HL, it should be feasible.

**Comment by player-03** [comment]
To be fair, it depends on the project. Updating my big project from OpenFL 3.6 took quite a while. It's hard to measure an exact amount of time because I took the opportunity to rewrite large chunks of the project, but it's safe to say OpenFL's changes contributed at least a month's worth of delay.

On the other hand, upgrading from Haxe 3 to 4 was smooth sailing. (It really does depend on the project!)

None of this is to say that Lime ought to back-port this feature. I think it's fine to declare that some features require Haxe 4, as long as the error message is clear.

**Comment by starry-abyss** [comment]
It's up to maintainers to decide anyway. I don't mind this ticket closed, but I won't close it because it does make sense to me.

> It took me one day to switch
Switching is not just compiling and running, switching is when there are no regressions left unfixed. And for that you need to test and find those regressions first.

**Comment by maitag** [comment]
backward-compatibility is allways good

**Comment by maitag** [comment]
(nobody should be left [or alone with older versions;])

**Comment by maitag** [comment]
best would be a fresh new Lime-Sample together with HXP (to choose optimal hashlink-vm version)

**Comment by maitag** [comment]
(^_^)
