### ISSUE TITLE
FileDialog->select(); leads to cast exception

### ISSUE THREAD

**Issue by manjav** [haxelime/lime#1404]
```
var fd = new FileDialog();
fd.onSelect.add(fd_onSelectHandler);
fd.browse();
...
function fd_onSelectHandler(text:String):Void {
	trace(text);
}
```
Exception has occurred.
Can't cast hl.bytes to String!

<local function> (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\ui\FileDialog.hx:80)
lime.app._Event_Dynamic_Void.dispatch (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\_internal\macros\EventMacro.hx:91)
lime.system.BackgroundWorker.sendComplete (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\system\BackgroundWorker.hx:82)
<local function> (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\ui\FileDialog.hx:50)
lime.app._Event_Dynamic_Void.dispatch (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\_internal\macros\EventMacro.hx:91)
lime.system.BackgroundWorker.__doWork (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\system\BackgroundWorker.hx:115)
lime.system.BackgroundWorker.run (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\system\BackgroundWorker.hx:67)
lime.ui.FileDialog.browse (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\ui\FileDialog.hx:111)
openfl.net.FileReference.browse (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\net\FileReference.hx:573)
ir.grantech.canvas.services.Layers.openAs (c:\_projects\_canvas\cansrc\src\ir\grantech\canvas\services\Layers.hx:77)
ir.grantech.canvas.controls.groups.Menu.lists_selectHandler (c:\_projects\_canvas\cansrc\src\ir\grantech\canvas\controls\groups\Menu.hx:96)
<local function> (c:\HaxeToolkit\haxe\lib\lime\7,7,0\src\lime\app\Module.hx:0)
openfl.events.EventDispatcher.__dispatchEvent (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\events\EventDispatcher.hx:402)
openfl.display.DisplayObject.__dispatchEvent (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\display\DisplayObject.hx:1425)
openfl.display.DisplayObject.__dispatchEvent (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\display\DisplayObject.hx:1441)
openfl.display.DisplayObject.__dispatchEvent (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\display\DisplayObject.hx:1441)
openfl.display.DisplayObject.__dispatchWithCapture (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\display\DisplayObject.hx:1486)
openfl.display.DisplayObject.dispatchEvent (c:\HaxeToolkit\haxe\lib\openfl\8,9,6\src\openfl\display\DisplayObject.hx:1143)
ir.grantech.canvas.events.CanEvent.dispatch (c:\_projects\_canvas\cansrc\src\ir\grantech\canvas\events\CanEvent.hx:30)
ir.grantech.canvas.controls.items.MenuItemRenderer.set_selected (c:\_projects\_canvas\cansrc\src\ir\grantech\canvas\controls\items\MenuItemRenderer.hx:51)

![{483F4757-6DEA-4BA0-BD37-DBF82BB3AEBC} png](https://user-images.githubusercontent.com/3495382/83301791-789d3800-a20f-11ea-92d4-e9b1fa64cf88.jpg)

**Comment by YRTV** [comment]
You can't just cast haxe.io.Bytes to String. Use haxe.io.Bytes.toString()

Valid code:
```
import haxe.io.Bytes;

class Main {
    static function main() {
        var originalString:String ="stringy";
        var stringAsBytes:Bytes = Bytes.ofString(originalString);
        var castBackToString:String = stringAsBytes.toString();
    }
}
```

Not valid code:
```
import haxe.io.Bytes;

class Main {
    static function main() {
        var originalString:String ="stringy";
        var stringAsBytes:Bytes = Bytes.ofString(originalString);
        var castBackToString:String = cast stringAsBytes;
    }
}
```
Uncaught exception: Can't cast haxe.io.Bytes to String
Called from $Main.main(Main.hx:7)
Called from fun$383(?:1)
