### ISSUE TITLE
haxelib run lime setup --quiet option

### ISSUE THREAD

**Issue by Wesss** [haxelime/lime#1425]
haxelib features a --quiet option that can be used to suppress the downloading progress output while downloading packages. I'd like to request this option for lime setup as well. I'm using lime in some CI, and these messages are flooding the output console and lagging the client.

**Comment by player-03** [comment]
I know you've probably moved on by now, but for anyone who stumbles across this question in the future, the thing to do is redirect output.

On *nix systems:

```bash
$ lime setup -y > /dev/null
```

On Windows:

```bash
$ lime setup -y > NUL
```

(Error messages will still print on *nix systems. Not sure about Windows.)
