### ISSUE TITLE
Improve help tag to show that you can set the location of the Project.xml

### ISSUE THREAD

**Issue by fabtjar** [haxelime/lime#1430]
The help tag didn't show how to pick the location of the Project.xml file.

Found it on https://lime.software/docs/command-line-tools/basic-commands/ but would be good if it was in the help text.

**Comment by player-03** [comment]
By "help tag," do you mean [the message that appears when you type `lime help`](https://github.com/haxelime/lime/blob/eac0c93b2c4c42f8e36fba21c0e0b501a53f4ca7/tools/CommandLineTools.hx#L777-L1086)?

**Comment by fabtjar** [comment]
I'm stupid!

```lime help test
Update, build and run in one command

Usage: lime test (project) <target> [options]```
