### ISSUE TITLE
System.fontsDirectory can return garbage on HashLink target

### ISSUE THREAD

**Issue by tour1st** [haxelime/lime#1441]
While testing my project on HashLink target, I noticed that TextFields (using OpenFL) didn't always render, like 50% of the time I started the app.
After further investigation, System.fontsDirectory doesn't always return a clean string, which makes the text engine fail to build a proper font path.
It looks like the buffer used to store the fonts directory isn't initialized or zero-terminated, so the conversion to a Haxe string can gives undetermined results.
However, other System.*directory accessors works 100% of the time.

Code sample :

```
import lime.system.System;

class Main
{
	static function main()
	{
		// Sometimes returns C:\Windows\Fonts\, sometimes C:\Windows\Fonts?#!\
		trace(System.fontsDirectory);
		
		// Always correct
		trace(System.applicationDirectory);
		trace(System.applicationStorageDirectory);
		trace(System.desktopDirectory);
		trace(System.documentsDirectory);
		trace(System.userDirectory);
	}
}
```

Setup : Windows 7, haXe 4.14, HashLink 1.11, Lime 7.8.0, OpenFL 9.0.2

**Comment by jgranick** [comment]
That's strange that it works for the other paths, yet not for fonts

https://github.com/haxelime/lime/blob/develop/project/src/backend/sdl/SDLSystem.cpp#L214

The code we use here for fonts is also the same code we use on Windows for the documents, user and desktop directories. I invite anyone to take a look and see if perhaps this code is a little off?

For HashLink, here is how the wstring is converted and returned. This might be the most suspicious part:

https://github.com/haxelime/lime/blob/develop/project/src/ExternalInterface.cpp#L2757-L2766

**Comment by tour1st** [comment]
You are right, it didn't make sense that it worked for other paths... until I managed to reproduce the same problem with `System.documentsDirectory` !
`C:\Windows\Fonts` is 16 characters long so I changed my documents folder location (in Windows settings) to a path that has a length multiple of 8, like `D:\ThisIsMyDocumentsPath` and now it fails too.
