### ISSUE TITLE
Add Support For Haxe 4.2

### ISSUE THREAD

**Issue by CanIGetaPR** [haxelime/lime#1450]
Lime currently doesn't work with Haxe 4.2 https://github.com/HaxeFoundation/haxe/releases/tag/4.2.0

**Comment by CanIGetaPR** [comment]
https://github.com/haxelime/lime/pull/1448

**Comment by japhib** [comment]
is this good to be closed?

**Comment by pozirk** [comment]
Works fine for me with Haxe 4.2.3, can be closed I think.

**Comment by player-03** [comment]
Works over here as well.
