### ISSUE TITLE
Error: Could not find haxelib "discord_rpc", does it need to be installed?

### ISSUE THREAD

**Issue by The-Last-Guard** [haxelime/lime#1455]
:**************>lime test windows
Warning: Lime version 7.9.0 may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use before to include a specific version
Error: Could not find haxelib "discord_rpc", does it need to be installed?

when trying to test something with "lime test windows" I get this one and I don't know how to correct it

please help me

**Comment by Apprentice-Alchemist** [comment]
The error tells you what's wrong.
You need to install the `discord_rpc` haxelib.
So run `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc` in the terminal. 

(Fun fact, the readme for Friday Night Funkin (I'm quite certain that's what you're trying to compile) tells you exactly which libs you need and how to install them.)

**Comment by The-Last-Guard** [comment]
thanks

**Comment by milestheboss** [comment]
this does not work for me please HELP ME

**Comment by joshtynjala** [comment]
> The error tells you what's wrong.
> You need to install the discord_rpc haxelib.
> So run haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc in the terminal.

> this does not work for me please HELP ME

Try exiting VSCode and then open your project again. Sometimes, after installing something with `haxelib`, restarting is necessary to get VSCode to recognize the new library.
