### ISSUE TITLE
iOS app crashes on the latest iOS15+ and new iPhone/iPad devices

### ISSUE THREAD

**Issue by pozirk** [haxelime/lime#1484]
Hey!

iOS app crashes on start on the latest iPhone/iPad devices with the latest iOS15+, for example, iPhone 12/13, iPad 9.
The might be something connected to the newest CPU and the way SharedObject saving/loading works.
From user's reports, app works on first start but crashes on subsequent launches.
There are some details about this problem here: https://community.stencyl.com/index.php?PHPSESSID=bec521f0b132387f6c1744259518fdaa&issue=2024.20

Thank you!

**Comment by justin-espedal** [comment]
Since Github Actions isn't cooperating right now, I've just gone ahead and started a PR here. If you have one of the problematic iOS devices, please test this!

https://github.com/haxelime/lime/pull/1485

**Comment by pozirk** [comment]
Hey Justin!
As I understand, I need to rebuild Lime for the change to work, right?
Thanks!

**Comment by justin-espedal** [comment]
Great! Since #1485 has been merged, I'll close this issue.
