### ISSUE TITLE
Can this be done one web?

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [haxelime/lime#1506]
If so how?

**Comment by player-03** [comment]
Are you talking about compiling a Lime app? Not normally, no. You might be able to pay someone to compile your code on their computer, but it's a lot easier just to install Haxe+Lime.

**Comment by LEVIXDDLMAO** [comment]
Thank you so much!

**Comment by player-03** [comment]
Glad to help.

By the way, here are some links:

[Install Haxe](https://haxe.org/download/) (required)
[Install HaxeFlixel](https://haxeflixel.com/documentation/install-haxeflixel/) (optional, but they have good [beginner tutorials](https://haxeflixel.com/documentation/tutorial/))
[Install OpenFL](https://www.openfl.org/download/) (also installs Lime)
[List of OpenFL tutorials](https://www.openfl.org/learn/haxelib/tutorials/)
